# The architecture choice is docker compose because then
# improves consistency, isolation, and reproducibility.
# For running the CLI inside a container it is a bit more overhead
# but we will improve it later with aliases and so on and so forth
services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: eventdb 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ..
      dockerfile: deploy/docker/Backend.Dockerfile
    container_name: backend
    depends_on:
      - db
    environment:
      # This URL will be repeated all over the deploys in all 
      # of the containers, we have to improve this and test it..
      DATABASE_URL: postgresql://devuser:devpass@db:5432/eventdb
      SECRET_KEY: dev-secret-key
    ports:
      - "8000:8000"

  collector:
    build:
      context: ..
      dockerfile: deploy/docker/Collector.Dockerfile
    container_name: collector
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://devuser:devpass@db:5432/eventdb
    ports:
      - "8001:8001"

  processor:
    build:
      context: ..
      dockerfile: deploy/docker/Processor.Dockerfile
    container_name: processor
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://devuser:devpass@db:5432/eventdb
    ports:
      - "8002:8002"

  alert_engine:
    build:
      context: ..
      dockerfile: deploy/docker/AlertEngine.Dockerfile
    container_name: alert_engine
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://devuser:devpass@db:5432/eventdb
    ports:
      - "8003:8003"

volumes:
  postgres_data:
